apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronicle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronicle
  template:
    metadata:
      labels:
        app: cronicle
    spec:
      containers:
        - name: cronicle
          image: jhuckaby/cronicle
          ports:
            - containerPort: 3012
          volumeMounts:
            - mountPath: /opt/cronicle/data
              name: cronicle-data
      volumes:
        - name: cronicle-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cronicle
spec:
  selector:
    app: cronicle
  ports:
    - port: 80
      targetPort: 3012
      protocol: TCP
